channels:
- conda-forge
dependencies:
- python=3.13.12
- pip<=26.2.1
- pip:
  - mlflow==3.16.1
  - lightgbm==4.7.0
  - numpy==2.5.3
  - pandas==3.0.6
  - psutil==7.2.2
  - pytest==9.1.1
  - scikit-learn==1.9.1
  - scipy==1.18.1
  - skops==0.15.0
name: mlflow-env
